@startuml Program
skinparam style strictuml
skinparam monochrome true


interface ASTNode {
    getLine(): int
    getColumn(): int
}

interface Statement
interface Definitions
class VarDef {
    variable: Variable
    type: Type
}

class FunDef {
    body:List<Statement>
    varDefs:List<VarDef>
    name: String
    type: FunType
}

class FuncType {
    params:List<VarDef>
    returnType: Type
}


FunDef o-- "0..n" Statement
FuncType <|.. Type

interface Type



class Program {
    definitions:List<Definitions>

}

ASTNode <|.. Program
Program  o-- "0..n" Definitions
ASTNode <|-- Definitions

Definitions <|.. VarDef
Definitions <|.. FunDef
FunDef o-- "0..n" VarDef
VarDef o-- "1" Type



@enduml
