@startuml Types
skinparam style strictuml
skinparam monochrome true

interface ASTNode {
    getLine(): int
    getColumn(): int
}

interface Type

ASTNode <|-- Type

interface SimpleType
interface ComplexType

class Array
class Struct

class IntType
class RealType
class CharType

Type <|.. SimpleType
Type <|.. ComplexType

ComplexType <|.. Array
ComplexType <|.. Struct

SimpleType <|.. IntType
SimpleType <|.. RealType
SimpleType <|.. CharType


@enduml
